name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ '*' ]

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
        go: ["1.19.x"]
    env:
      COVERAGES: ""
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os}} (go ${{ matrix.go }})
    defaults:
      run:
        working-directory: go-car-mirror
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: go-car-mirror
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Go information
        run: |
          go version
          go env
      - name: Build
        run: make build
      - name: Run unit tests
        run: make test
      - name: Check formatted
        run: gofmt -l .
